Formation = {
    "ESIEE-IT_724787_PO_INGENIEUR_Cycle Préparatoire intégré en 2 ans_TP_ING1/ING2"
    "ESIEE-IT_1007730_PA_INGENIEUR_Cycle Préparatoire intégré en 2 ans_TP_ING1/ING2"
    "ESIEE-IT_724783_PO_INGENIEUR_Cycle Ingénieur en 3 ans_ALT_ING3/ING4/ING5"
    "ESIEE-IT_533323_CC_BACHELOR_ALT_Développeur de solutions web et mobile (Diplôme : Développeur de Solutions Numériques Sécurisées)"
    "ESIEE-IT_490601_CC_BACHELOR_TP_Développeur de solutions web et mobile (Diplôme : Développeur de Solutions Numériques Sécurisées)"
    "ESIEE-IT_533326_CP_BACHELOR_ALT_Développeur de solutions web et mobile (Diplôme : Développeur de Solutions Numériques Sécurisées)"
    "ESIEE-IT_490603_CP_BACHELOR_TP_Développeur de solutions web et mobile (Diplôme : Développeur de Solutions Numériques Sécurisées)"
    "ESIEE-IT_524826_PO_BACHELOR_Informatique_TP (Cyber, IA, Ingé log, Robotique & Smart Green Building)_(Diplôme : Développeur de Solutions Numériques Sécurisées)"
    "ESIEE-IT_525436_PO_BACHELOR_Informatique_ALT (Cyber, IA, Ingé log, Robotique & Smart Green Building)_ (Diplôme : Développeur de Solutions Numériques Sécurisées)"
    "ESIEE-IT_1008114_PO_Double diplôme_BACHELOR_Informatique/Licence CNAM_ALT_B3 (Diplôme : Développeur de Solutions Numériques Sécurisées)"
    "ESIEE-IT_1008093_CP_M2I_Lead Dev_ALT_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1008097_CP_M2I_Lead Dev_TP_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1005487_PO_M2I_Lead Dev_ALT_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1008105_PO_M2I_Lead Dev_TP_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1005486_PO_M2I_Développeur VR & Jeux Vidéo_ALT_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1008103_PO_M2I_Développeur VR & Jeux Vidéo_TP_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_926771_PO_E3IN_Cybersécurité_ALT_Bac+4/Bac+5 (Diplôme : Expert en ingénierie informatique et innovation numérique)"
    "ESIEE-IT_930246_PO_E3IN_Cybersécurité_TP_Bac+4/Bac+5 (Diplôme : Expert en ingénierie informatique et innovation numérique)"
    "ESIEE-IT_926772_PO_E3IN_Intelligence Artificielle & Big Data_ALT_Bac+4/Bac+5 (Diplôme : Expert en ingénierie informatique et innovation numérique)"
    "ESIEE-IT_930247_PO_E3IN_Intelligence Artificielle & Big Data_TP_Bac+4/Bac+5 (Diplôme : Expert en ingénierie informatique et innovation numérique)"
    "ESIEE-IT_926773_PO_E3IN_Ingénierie Logicielle & Management des Systèmes d'Information_ALT_Bac+4/Bac+5 (Diplôme : Expert en ingénierie informatique et innovation numérique)"
    "ESIEE-IT_930248_PO_E3IN_Ingénierie Logicielle & Management des Systèmes d'Information_TP_Bac+4/Bac+5 (Diplôme : Expert en ingénierie informatique et innovation numérique)"
    "ESIEE-IT_1005481_PO_M2I_Robotique & innovations technologiques_ALT_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1008107_PO_M2I_Robotique & innovations technologiques_TP_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1008109_PO_M2I_Smart  & Green Building_ALT_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_1005480_PO_M2I_Smart  & Green Building_TP_Bac+4/Bac+5 (Diplôme : Manager en ingénierie informatique)"
    "ESIEE-IT_502165_PO_CONSULTANT_EN_BUSINESS_ANALYSE_ALT_Bac+5"
    "ESIEE-IT_874657_PO_CONSULTANT_EN_BUSINESS_ANALYSE_TP_Bac+5"
}